org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10

#Fabric api
fabric_version=0.115.1+1.21.1

mod_version = 1.0.0-beta.30
maven_group = io.github.foundationgames
archives_base_name = phonos

jsonem_version=0.3+1.21
modmenu_version=11.0.3

# YACL - https://docs.isxander.dev/yet-another-config-lib/installing-yacl
yacl_version = 3.6.1+1.21-fabric

# Simple Voice Chat - https://modrepo.de/minecraft/voicechat/api/getting_started
# https://maven.maxhenkel.de/#/releases/de/maxhenkel/voicechat/voicechat-api
# https://modrinth.com/plugin/simple-voice-chat
voicechat_api_version = 2.5.0
voicechat_version = 1.21.1-2.5.26
enable_simple_voice_chat = true

# Create - Fabric
# https://modrinth.com/mod/create-fabric/versions
create_fabric_version = 0.5.1-f-build.1490+mc1.20.1
enable_create = false

# Music Disc Testing
enable_music_disc_mods = true

# More Music Discs - https://modrinth.com/mod/more-music-discs/versions
more_music_discs_version = 1.21.1-34-fabric
